## Numpy Notes

### 1. Basic

#### 1.1 ndarray 
numpy array is an object of ndarray

In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
type(a)

numpy.ndarray

| Attribute | Description          
| :- |:------------- |
|ndarray.ndim| The number of axes(dimensions).
|ndarray.shapes |A tuple indicate the size of each dimensions
|ndarray.size |total number of elements
|ndarray.dtype| type of elements
|ndarray.itemsize | equivelent to ndarray.dtype.itemsize

In [7]:
print("dim ", a.ndim)
print ('size', a.shape)
print('dtype', a.dtype)
print('itemsize', a.itemsize)

dim  2
size (3, 5)
dtype int32
itemsize 4


## Array Creation
### 2.1 Create array from python list or tuple

In [23]:
a = np.array([2,3,4])
b = np.array([(1,2,3),(2,3,4)])
c = np.array([[1,2],[3,4]], dtype = 'complex')

print ('\nnp.array([2,3,4]) -->', a)
print ('\nnp.array([(1,2,3),(2,3,4)]) -->\n', b)
print ("\nnp.array([[1,2],[3,4]], dtype = 'complex') -->\n", c)


np.array([2,3,4]) --> [2 3 4]

np.array([(1,2,3),(2,3,4)]) -->
 [[1 2 3]
 [2 3 4]]

np.array([[1,2],[3,4]], dtype = 'complex') -->
 [[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


### 2.2 Create zero and one arrays

In [24]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])