

## Numpy Notes

### 1. Basic

#### <span style="color:orange">1.1 ndarray</span>
numpy array is an object of ndarray

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
type(a)

numpy.ndarray

| Attribute | Description          
| :- |:------------- |
|ndarray.ndim| The number of axes(dimensions).
|ndarray.shapes |A tuple indicate the size of each dimensions
|ndarray.size |total number of elements
|ndarray.dtype| type of elements
|ndarray.itemsize | equivelent to ndarray.dtype.itemsize

In [7]:
print("dim ", a.ndim)
print ('size', a.shape)
print('dtype', a.dtype)
print('itemsize', a.itemsize)

dim  2
size (3, 5)
dtype int32
itemsize 4


## 1.2 Array Creation
### 1.2.1 Create array from python list or tuple

In [23]:
a = np.array([2,3,4])
b = np.array([(1,2,3),(2,3,4)])
c = np.array([[1,2],[3,4]], dtype = 'complex')

print ('\nnp.array([2,3,4]) -->', a)
print ('\nnp.array([(1,2,3),(2,3,4)]) -->\n', b)
print ("\nnp.array([[1,2],[3,4]], dtype = 'complex') -->\n", c)


np.array([2,3,4]) --> [2 3 4]

np.array([(1,2,3),(2,3,4)]) -->
 [[1 2 3]
 [2 3 4]]

np.array([[1,2],[3,4]], dtype = 'complex') -->
 [[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


### 1.2.2 Create zero and one arrays

In [24]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [4]:
np.random.random((2,3))

array([[ 0.39077589,  0.18725504,  0.14236906],
       [ 0.56133714,  0.39402669,  0.82799433]])

In [5]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### 1.2.3 arange

In [27]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [29]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

### 1.2.4 reshape


In [31]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
ra = np.arange(6,12)
ra1 = ra.reshape(2,3)
ra1
ra1.reshape(3,2)

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

## 1.3 Basic Operations 

### Accessing array elements

In [12]:
print ra1[0,1]

7


In [20]:
squareArray = np.arange(1,10).reshape(3,3)
print squareArray[0:2,0:2]
print squareArray[0]
print squareArray[0, 1:2]
print squareArray[0,2]

[[1 2]
 [4 5]]
[1 2 3]
[2]
3


In [ ]:
# set last row to ones
squareArray[2] =1
print squareArray

### Operations

In [40]:
a = np.array([20,30,40,50])
b = np.arange(4)
print('a: \t', a)
print('b: \t', b)
print('a-b: \t', a -b)
print ('a*b: \t', a*b)
print('10*np.sin(a):', 10*np.sin(a))

a: 	 [20 30 40 50]
b: 	 [0 1 2 3]
a-b: 	 [20 29 38 47]
a*b: 	 [  0  30  80 150]


In [26]:
# average
print 'Average: ', np.average(squareArray)
print 'Standard deviation: ', np.std(squareArray)

#

Average:  2.66666666667
Standard deviation:  1.82574185835


In [45]:
squareArray = np.arange(1,10).reshape(3,3)
sqAverage = np.average(squareArray)

betterThanAverage = squareArray > sqAverage
print 'Better Than Average: ',  betterThanAverage

print 'Index of BetterThanAverage: ' , squareArray[betterThanAverage]

print 'Average: ', sqAverage
sqStdDev = np.std(squareArray)
print 'Standard Deviation: ', sqStdDev
clampedSqArray = np.array(squareArray.copy(), dtype=float)
print clampedSqArray

clampedSqArray[(squareArray-sqAverage) > sqStdDev] = sqAverage + sqStdDev
#calampedSqArray[(squareArray-sqAverage) < -sqStdDev] = sqAverage -sqStDev
print clampedSqArray

Better Than Average:  [[False False False]
 [False False  True]
 [ True  True  True]]
Index of BetterThanAverage:  [6 7 8 9]
Average:  5.0
Standard Deviation:  2.58198889747
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 1.         2.         3.       ]
 [ 4.         5.         6.       ]
 [ 7.         7.5819889  7.5819889]]


# Questions

## Q1. How many ways to get a column of array?




In [8]:
 #Create a array, Get Column 1 as a list
a = np.arange(12).reshape(4,3)
print(a)
print
print ("Get column 1, Method 1: a[:, 1]")

print (a[:,1])

print ("Get column 1, Method 2: list extension")
b = [example[1] for example in a]
print (b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Get column 1, Method 1: a[:, 1]
[ 1  4  7 10]
Get column 1, Method 2: list extension
[1, 4, 7, 10]


### numpy.where

first parameter is conditon: if condition is ture, choose value from x, else choose value from y

if without x, y return idexes of True

In [2]:
import numpy as np
np.where([[True,False],[True,True]], [[1,2],[3,4]],[[9,8],[7,6]])

array([[1, 8],
       [3, 4]])

In [9]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.where(x>5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [10]:
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
x >5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]], dtype=bool)